server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    
spring:
 application:
  name: Eureka-Server1
    
logging:
 level:
  com:
   netflix:
    eureka: OFF
    
    discovery: OFF