server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yogesh-ss/SpringBootTest.git     # file:///C:/GitRepository/SpringBootTest
          #username: 
          #password: 
          #timeout: 20
          #clone-on-start: true